name: keframe
description: Helps you improve the fluency of Flutter's app for any scenario
version: 2.0.3
homepage: https://github.com/LianjiaTech/keframe

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
